import { z } from "zod";

/**
 * Narration audio manifest (docs/06, B4): one audio file per narrative
 * section, with word-level timings for the synced transcript. Generated by
 * `npm run audio` (scripts/generate-audio.ts), committed alongside the
 * content, validated by content tests: `textHash` pins the narration to the
 * prose it was generated from, so drifted audio is a red build, not a
 * silent lie (C3's audio-staleness discipline).
 */

export const WordTimingSchema = z.object({
  /** The word exactly as it appears in the prose (whitespace-split). */
  w: z.string().min(1),
  /** Start/end in seconds. */
  s: z.number().min(0),
  e: z.number().min(0),
});

export const AudioSectionSchema = z.object({
  /** "hook" or a story section id. */
  id: z.string().min(1),
  /** sha256 of the narration text this audio was generated from. */
  textHash: z.string().length(64),
  /** Public path of the mp3, e.g. /audio/linear-regression/hook.mp3 */
  src: z.string().startsWith("/audio/"),
  durationSeconds: z.number().positive(),
  words: z.array(WordTimingSchema).min(1),
});

export const AudioManifestSchema = z.object({
  nodeId: z.string().min(1),
  voiceId: z.string().min(1),
  modelId: z.string().min(1),
  generatedAt: z.string().min(1),
  sections: z.array(AudioSectionSchema).min(1),
});

export type WordTiming = z.infer<typeof WordTimingSchema>;
export type AudioSection = z.infer<typeof AudioSectionSchema>;
export type AudioManifest = z.infer<typeof AudioManifestSchema>;

export { sectionText, splitWords } from "./words";
